# -----------------------------------------------------------
# Installs php dependencies
# -----------------------------------------------------------

# Add ondrej PPA
- name: Add ondrej/php PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/phpo'
    state: present

# Installs PHP and other dependencies
- name: PHP and other dependencies
  ansible.builtin.apt:
  pkg:
  - curl
  - php8.1
  - php8.1-curl
  - php8.1-dev
  - php8.1-gd
  - php8.1-mbstring
  - php8.1-zip
  - php8.1-mysql
  - php8.1-xml
  - php-token-stream
  - php8.1-opcache
  - libapache2-mod-php8.1
  - php8.1-cli
  - php8.1-common
  - php8.1-ffi
  - php8.1-igbinary
  - php8.1-memcached
  - php8.1-msgpack
  - git
  - supervisor
  